name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00

jobs:
  api-tests:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: '9.0.x'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run API tests
        continue-on-error: true
        run: dotnet test ./Tests/API/TestGetUsers.cs --logger "trx;LogFileName=api_tests.trx" --results-directory ./TestResults
      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: ./TestResults/

  ui-tests:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: '9.0.x'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run UI tests
        run: dotnet test ./Tests/TestArticleTitle.cs --logger "trx;LogFileName=ui_tests.trx" --results-directory ./TestResults -- TestBrowser=${{ github.event.inputs.browser || 'chrome' }}
      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: ./TestResults/
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ./Screenshots/
